import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Video, Calendar, Users, Clock, Settings, Search, Plus, Sparkles, Hash } from 'lucide-react';
import { BACKEND_URL } from '../config';
import { io } from 'socket.io-client';
import MeetingCreatedModal from '../components/MeetingCreatedModal';
import IncomingCallModal from '../components/IncomingCallModal';
import './Dashboard.css';

const Dashboard = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('home');
  const [joinCode, setJoinCode] = useState('');
  const [isCreating, setIsCreating] = useState(false);
  const [joinError, setJoinError] = useState('');
  
  const [createdMeetingCode, setCreatedMeetingCode] = useState(null);
  const [incomingCall, setIncomingCall] = useState(null);

  React.useEffect(() => {
    // Listen for incoming calls globally on dashboard
    // We mock the user ID as we did in backend for now
    const dummyUserId = "dummy-user-id"; // In real app, this comes from AuthContext
    const socket = io(BACKEND_URL, { transports: ['websocket'] });
    
    // We don't know the exact dummy user ID generated by Prisma, 
    // so we can't reliably subscribe to `invite-received-${receiver.id}` 
    // without fetching the user profile first. 
    // For demo purposes, we'll listen to a generic broadcast if needed,
    // but the backend uses `invite-received-${receiver.id}`.
    // Let's assume the user email is 'demo@linguaverse.com' and fetch their ID.
    fetch(`${BACKEND_URL}/auth/me`) // Assuming a future endpoint, but let's mock it
      .catch(() => {});

    // Hack for prototype: listen to ALL incoming calls and show them.
    socket.onAny((eventName, ...args) => {
      if (eventName.startsWith('invite-received-')) {
        setIncomingCall(args[0]);
      }
    });

    return () => socket.disconnect();
  }, []);

  const handleCreateMeeting = async () => {
    setIsCreating(true);
    try {
      const response = await fetch(`${BACKEND_URL}/meetings/create`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title: 'Instant Meeting' })
      });
      const data = await response.json();
      if (data.meetingCode) {
        setCreatedMeetingCode(data.meetingCode);
      }
    } catch (err) {
      console.error('Failed to create meeting', err);
      alert('Failed to connect to backend server. Ensure it is running.');
    } finally {
      setIsCreating(false);
    }
  };

  const handleJoinMeeting = async (e) => {
    e.preventDefault();
    setJoinError('');
    let code = joinCode.trim();
    if (!code) return;
    
    if (code.includes('/meet/')) {
      code = code.split('/meet/').pop();
    }
    
    try {
      const response = await fetch(`${BACKEND_URL}/meetings/validate/${code}`);
      const data = await response.json();
      
      if (response.ok && data.valid) {
        navigate(`/meet/${code}`);
      } else {
        setJoinError(data.message || 'Meeting not found.');
      }
    } catch (err) {
      setJoinError('Failed to connect to server.');
    }
  };

  return (
    <div className="dashboard-container">
      {/* Sidebar */}
      <div className="dash-sidebar glass">
        <div className="dash-logo">
          <Sparkles className="text-primary" />
          <span>LinguaVerse</span>
        </div>
        
        <nav className="dash-nav">
          <button className={`nav-item ${activeTab === 'home' ? 'active' : ''}`} onClick={() => setActiveTab('home')}>
            <Video size={20} /> Home
          </button>
          <button className={`nav-item ${activeTab === 'contacts' ? 'active' : ''}`} onClick={() => setActiveTab('contacts')}>
            <Users size={20} /> Contacts
          </button>
          <button className={`nav-item ${activeTab === 'history' ? 'active' : ''}`} onClick={() => setActiveTab('history')}>
            <Clock size={20} /> History
          </button>
          <button className={`nav-item ${activeTab === 'settings' ? 'active' : ''}`} onClick={() => setActiveTab('settings')}>
            <Settings size={20} /> Settings
          </button>
        </nav>

        <div className="dash-user">
          <div className="avatar">P</div>
          <div className="user-info">
            <span className="name">Priya</span>
            <span className="plan">Pro Plan</span>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="dash-main">
        <div className="dash-header">
          <div className="search-bar glass">
            <Search size={18} className="text-muted" />
            <input type="text" placeholder="Search meetings, contacts..." />
          </div>
          <div className="date-display">
            {new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}
          </div>
        </div>

        <div className="dash-content">
          <div className="dash-hero">
            <div className="time-greeting">
              <h1>Good Morning, Priya</h1>
              <p>Ready to connect with the world?</p>
            </div>
          </div>

          <div className="action-cards">
            <motion.div 
              className="action-card primary glass-card"
              whileHover={{ scale: 1.02 }}
              onClick={handleCreateMeeting}
              style={{ opacity: isCreating ? 0.7 : 1, pointerEvents: isCreating ? 'none' : 'auto' }}
            >
              <div className="icon-wrapper"><Video size={28} /></div>
              <h3>{isCreating ? 'Generating...' : 'New Meeting'}</h3>
              <p>Start an instant AI translated meeting</p>
            </motion.div>

            <motion.div className="action-card join glass-card" whileHover={{ scale: 1.02 }}>
              <div className="icon-wrapper"><Hash size={28} /></div>
              <h3>Join Meeting</h3>
              <form onSubmit={handleJoinMeeting} className="join-form">
                <input 
                  type="text" 
                  placeholder="Enter 12-digit code" 
                  value={joinCode}
                  onChange={(e) => { setJoinCode(e.target.value); setJoinError(''); }}
                />
                <button type="submit">Join</button>
              </form>
              {joinError && <div style={{ color: '#ff4444', fontSize: '0.8rem', marginTop: '8px' }}>{joinError}</div>}
            </motion.div>

            <motion.div className="action-card schedule glass-card" whileHover={{ scale: 1.02 }}>
              <div className="icon-wrapper"><Calendar size={28} /></div>
              <h3>Schedule</h3>
              <p>Plan a meeting for later</p>
            </motion.div>
          </div>

          <div className="upcoming-meetings">
            <h2>Upcoming Meetings</h2>
            <div className="meeting-list">
              <div className="meeting-item glass">
                <div className="m-time">
                  <span className="m-hour">10:00 AM</span>
                  <span className="m-duration">45 Min</span>
                </div>
                <div className="m-details">
                  <h4>Global Marketing Sync</h4>
                  <p>English ➔ Japanese | 4 Participants</p>
                </div>
                <button className="btn-secondary small">Start</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <MeetingCreatedModal 
        isOpen={!!createdMeetingCode} 
        meetingCode={createdMeetingCode} 
        onClose={() => setCreatedMeetingCode(null)} 
      />

      <IncomingCallModal 
        invitation={incomingCall} 
        onAccept={() => setIncomingCall(null)} 
        onDecline={() => setIncomingCall(null)} 
      />
    </div>
  );
};

export default Dashboard;
